messages-api:
  url: 'http://localhost:9090/hello'

spring:
  security:
    oauth2:
      client:
        registration:
          spring:
            scope: openid,profile
            client-id: spring
            client-secret: secret
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9000